-- AlterTable
ALTER TABLE "Offre" ALTER COLUMN "montant" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Propriete" ALTER COLUMN "prix" SET DATA TYPE BIGINT,
ALTER COLUMN "surface" SET DATA TYPE BIGINT;
